### ISSUE TITLE
Filter by version

### ISSUE THREAD

**Issue by CydGoblin** [tailwindcomponents/issue-tracker#1]
**Describe your Idea**
Add the ability to filter result by version of tailwind, could be by mayor releases

**Additional context**
Tailwind is now on v2 and there's a lot of old components no longer compatible. The version is already on the details.

**Comment by khatabwedaa** [comment]
it's a great idea @Turqueso I will do it as fast as I can ⚡🤝.

**Comment by khatabwedaa** [comment]
It's Ready we will publish it today :1st_place_medal:
