### ISSUE TITLE
Access to favorite component

### ISSUE THREAD

**Issue by ahangarha** [tailwindcomponents/issue-tracker#2]
**Describe your Idea**
Currently one can like a component but there is not way to access them again in future.

**Additional context**
It should be easy to implement this feature for logged in users to access their favorite components. The list can also be sorted by given rate of the user.

**Comment by ahangarha** [comment]
I don't know if it is newly added or I didn't pay attention to it but there is an option to add a component to favorites.

Yet it would be good to have access to rated components as well.

I close the issue.

**Comment by khatabwedaa** [comment]
The favorites components can be accessible in https://tailwindcomponents.com/u/mostafa-ahangarha/favorites and you can find the link in the user dropdown
