### ISSUE TITLE
Enable JIT support

### ISSUE THREAD

**Issue by maddog986** [tailwindcomponents/issue-tracker#4]
**Describe your Idea**
JIT support would be nice. Having the ability to use peer-* on components opens a ton more possibilities for components.

**Additional context**
I built a simple carousel component, but can not submit due to it using peer-* styling. See it at https://play.tailwindcss.com/bzje1DhMN5

**Comment by agustinprod** [comment]
It's actually  a nice thing to have, because we're loading the full tailwindcss for each component, a few mb worth of css... We should generate a tailwind css compilation on real time by compiling on the browser, but i don't know if that is possible.

**Comment by maddog986** [comment]
> It's actually a nice thing to have, because we're loading the full tailwindcss for each component, a few mb worth of css... We should generate a tailwind css compilation on real time by compiling on the browser, but i don't know if that is possible.

Would this work? https://github.com/beyondcode/tailwindcss-jit-cdn

**edit:** Appears to work for me, testing locally, with a simple html file and the included script tag.
**edit: edit:** Working demo, with Tailwind JIT: https://codesandbox.io/s/infallible-wing-nqsjx?file=/index.html

**Comment by agustinprod** [comment]
It looks exactly what we need, thank you! Maybe we should only enable this for components on version >= 2.0. What do you think @khatabwedaa  ?

**Comment by khatabwedaa** [comment]
Let take look :eyes: .

**Comment by maddog986** [comment]
Just now I guess we can just add the script tag to the component page, it works: https://tailwindcomponents.com/component/card-carousel

**Comment by khatabwedaa** [comment]
Awesome I will apply it for all v2 components Thanks Budy.

**Comment by khatabwedaa** [comment]
Hey @maddog986, we added to the code base now you can use jit without including any script.
